### ISSUE TITLE
Hello,im A new bee of Dlang,im build Dgui got a Error ?

### ISSUE THREAD

**Issue by sgf** [o3o/dguihub#3]
Building Win32\Debug\dgui.lib...
D:\Dev\D\dmd2\windows\bin\..\..\src\druntime\import\core\time.d(80): Error: module dgui.core.exception from file core\exception.d must be imported with 'import dgui.core.exception;'
Building Win32\Debug\dgui.lib failed!

how can i do for this problem?

**Comment by o3o** [comment]
Hi sgf
what operating system do you use? WinXp? Win10?

**Comment by sgf** [comment]
@o3o Hi,mate,im Use Windows10
but im not sure about the problem,maybe it's the VisualD 's Bug ?
but i cant find Issue(Lick) on VisualD's Project  (https://github.com/dlang/visuald)
maybe VisualD is cant distinguish 
the DMD's core.exception; and
DGUI's dgui.core.exception;

**Comment by sgf** [comment]
where,when i rename the "Core" folder to "forms",then compile passed.

**Comment by sgf** [comment]
thank u reply
